- hubedit/src/main.rs
- hubtools/Cargo.toml
- hubtools/src/lib.rs
Here's an example of what this produces:
```
[
("GITC", [
"3642072b886fb76b1312afc25aad3333ac9b5cba-dirty",
]),
("BORD", [
"stm32g070",
]),
("NAME", [
"demo-stm32g070-nucleo",
]),
("VERS", [
"0.1.3",
]),
]
```
(taking roughly 156 bytes)
> Add functions to write a sensible default caboose

- hubedit/src/main.rs
- hubtools/Cargo.toml
- hubtools/src/lib.rs
This PR started as an attempt to improve how we handle the internal segment maps, and quickly spiraled out of control.
Broadly, the PR implements a new workflow:
- ELF files are loaded into a `RawHubrisImage`
- Internally, a `RawHubrisImage` is a `Vec<u8>` of flash contents, a starting address, and a kernel entry point
- A `RawHubrisImage` can be converted back into ELF or `.bin`
This can happen either inside or outside of a `RawHubrisArchive`; `hubedit` uses the former, and Hubris' build system uses the latter.
Note that this eliminates the IHEX and SREC files from the Hubris archive!  This is fine; no one was using them anyways (Humility generates them on-demand from the ELF).
> Refactoring and cleanup

- hubedit/src/main.rs
- hubtools/Cargo.toml
- hubtools/src/lib.rs
This PR adds support for LPC55 operations, e.g. signing and verifying images.
It needs to be merged after https://github.com/oxidecomputer/lpc55_support/pull/31
> Add LPC55 operations

- hubtools/src/lib.rs
With the RFD374 stage0 transition, Hubris archives will sport one of two magic numbers to frighten and confuse old-stage0. The header layouts are the same, though, so the impact to hubtools is limited to teaching it that either number is okay.
While I was here, though, I also marginally improved diagnostics in the event of a magic number mismatch, since that's how I got here in the first place.
> Tolerate old and new magic numbers

- hubtools/Cargo.toml
- hubtools/src/lib.rs
Also support the new `use_rsa_4096` flag to `generate_cmpa` and the new `image_key_revoke` argument to `generate_cfpa`.
Depends on [lpc55_support#58](https://github.com/oxidecomputer/lpc55_support/pull/58).
> Use new x509_cert::Certificate interface to lpc55_sign

- hubtools/src/caboose.rs
- hubtools/src/lib.rs
This adds a handful of things that would let MGS use `hubtools` instead of having its own hubris archive stuff:
1. `RawHubrisArchive` can be opened from a `Vec<u8>`, not just a file on disk
2. Add an `auxiliary_image()` helper method
3. Make `read_caboose()` return a `Caboose` instead of a `Vec<u8>`, and add a method on `Caboose` to parse and read the `BORD` value
(MGS doesn't do the 3rd item today, but it would be nice if it could!).
> Add utilities to make hubtools suitable for use in MGS

- hubedit/Cargo.toml
- hubedit/src/main.rs
- hubtools/Cargo.toml
- hubtools/src/lib.rs
Canonical CMPA / CPFA comes from bootleby; these files are unused and we're them from the Hubris archive in https://github.com/oxidecomputer/hubris/pull/1411
> Remove commands which assume the presence of cmpa/cfpa in the archive

- hubtools/Cargo.toml
- hubtools/src/lib.rs
Previously, images that used inheritance had the `NAME` of the parent file in their caboose.  This PR switches over to using the patched name instead.
> Set NAME as the patched name when `patches.toml` is present

- hubtools/src/archive_builder.rs
- hubtools/src/caboose.rs
- hubtools/src/lib.rs
My immediate goal with this is to be able to generate _fake_ hubris archives for integration tests in omicron, and as of this PR `HubrisArchiveBuilder` is probably only useful for that. I tried not to close the door on it potentially being useful to generate a real hubris archive from a standalone image, but it will need some additions for that to be useful (e.g., adding an `app.toml` for humility).
> Add `HubrisArchiveBuilder` to create hubris archives from raw images or thin air

- hubedit/src/main.rs
- hubtools/src/lib.rs
Verify that a particular binary will work with a specified CMPA/CFPA combination
> Add verify command for lpc55

- Cargo.toml
- hubtools/Cargo.toml
- hubtools/src/caboose.rs
- hubtools/src/lib.rs
For use with permission slip for signing/tagging artifacts, add an API to remove a signature and prep an image for signing.
> Add hubris re-stamp function

- hubtools/Cargo.toml
- hubtools/src/lib.rs
This only affects images being signed for the first time
> Ignore error from unsign and clippy fixes

- hubtools/Cargo.toml
- hubtools/src/lib.rs
We're going to sign the stm32h7 but not actually append it to the image until we figure out what makes sense
> Save the signature for non lpc55 targets

- hubtools/Cargo.toml
- hubtools/src/bootleby.rs
- hubtools/src/caboose.rs
- hubtools/src/lib.rs
It's useful to have some information about what was used to sign an archive, add the hash of the root certs as a piece of identifying information
> Append SIGN information in the caboose

- rust-toolchain.toml
Specify a newer toolchain to avoid issues with clap
```
error: package `clap v4.5.0` cannot be built because it requires rustc
1.74 or newer, while the currently active rustc version is 1.72.1
```
> Add a rust toolchain

- hubtools/src/lib.rs
Derive Clone on RawHubrisArchive to make it a bit more useful.
> Need to derive Clone on RawHubrisArchive for faux-mgs work.

- Cargo.lock
- Cargo.toml
- fwidgen/Cargo.toml
- fwidgen/src/main.rs
This is an attempt to replace the `img/final.fwid` file generated by hubris `xtask` in the archive with a tool that can calculate t he value on demand. If we like the approach I'd like to extend this tool (or add another) to check the signature over the firmware image as a mechanism to establish trust in the FWID value.
> fwidgen: Add tool to generate FWID for the image in a hubris archive.

- Cargo.lock
- fwidgen/Cargo.toml
- fwidgen/src/main.rs
this resolves both #40 and #41 since it turns out they're pretty closely related
> fwidgen: allow caller to select the FWID digest, add support for sha256, add IANA string id to output

- fwidgen/src/main.rs
- hubtools/src/lib.rs
We do some work here to preserve the existing behavior of the `is_lpc55` function to keep from breaking API compatibility.
this resolves #39
> Move `enum Chip` from fwidgen to hubtools lib.

- hubtools/src/lib.rs
This change was not needed. We don't need clone on these large structs.
> Revert previous commit that derived Clone on RawHubrisArchive and RawHubrisImage

- Cargo.lock
- fwidgen/src/main.rs
- hubtools/Cargo.toml
- hubtools/src/lib.rs
This implementation allows the caller to use any hash algorithm that implements the `Digest` trait from the `digest` crate.
> Move FWID generation code into hubtools::RawHubrisArchive.

- hubtools/src/lib.rs
This will be used in oxidecomputer/omicron#8060.
> allow reading caboose from Hubris image
